# Generated by Django 2.2.8 on 2019-12-16 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []
    # dependencies = [
    #     migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    #     ('meeting_room', '0021_auto_20191216_1244'),
    # ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('meeting_room_name', models.FloatField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Комната переговоров')),
                ('amount_of_chairs', models.PositiveIntegerField(default=0, verbose_name='Количество стульев')),
                ('projector', models.BooleanField(default=0, verbose_name='Проектор')),
                ('flip_chart', models.BooleanField(default=0, verbose_name='Флипчарт')),
                ('description', models.CharField(default='', max_length=200, verbose_name='Описание переговорной')),
            ],
            options={
                'verbose_name': 'Переговорная',
                'verbose_name_plural': 'Переговорные',
                'permissions': (('change', 'Может изменять атрибутивный состав переговорных'),),
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(default=None, verbose_name='Дата начала')),
                ('time_end', models.DateTimeField(default=None, verbose_name='Дата окончания')),
                ('approved_flag', models.PositiveSmallIntegerField(choices=[(1, 'На рассмотрении'), (2, 'Одобрено'), (3, 'Отказано')], default=1, verbose_name='Статус')),
                ('reserved_time', models.CharField(blank=True, default='', max_length=11, verbose_name='Время бронирования')),
                ('reserved_date', models.CharField(blank=True, default='', max_length=12, verbose_name='Дата бронирования')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Комментарий')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meeting_room', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='meeting_room.MeetingRoom')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'permissions': (('accept_decline_bid', 'Может подтверждать заявки'),),
            },
        ),
    ]
