# Generated by Django 2.2.8 on 2019-12-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_room', '0022_bid_meetingroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='meeting_room_name',
            field=models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Комната переговоров'),
        ),
    ]
